### ISSUE TITLE
Ошибка форматирования в lw1

### ISSUE THREAD

**Issue by veresnikov** [DanielZabolotskih/web-development#1]
&lt;?phpecho 'Hello World!';

[https://github.com/DanielZabolotskih/web-development/blob/master/lw1/world.php](url)

**Comment by KirillVeresnikov** [comment]
`<!--StartFragment-->&lt;?phpecho 'Hello World!';<!--EndFragment-->`
> [https://github.com/DanielZabolotskih/web-development/blob/master/lw1/world.php](url)

**Comment by DanielZabolotskih** [comment]
Исправлено
d5a7c63e97a6a1a7d360a6ac0598c8165aaa772b
